package diploma.webcad.core.model.trigger;

public enum TriggerJobType {
	
	TEST,
	CONTEST_START_REQUEST_ACCEPTING, 
	CONTEST_END_REQUEST_ACCEPTING, 
	CONTEST_START_WORK_ACCEPTING, 
	CONTEST_END_WORK_ACCEPTING,
	CONTEST_START_VOTING, 
	CONTEST_END_VOTING, 
	CONTEST_FINISHING, 
	CONTEST_AWARDING,
	CONTEST_FREZZED,
	CONTEST_STOPPING;
}
