package diploma.webcad.core.model;

public enum EventType {
	
	CONTEST_CANCELLED,
	CONTEST_CHANGE_PARAMETER,
	CONTEST_COMMENTED,
	CONTEST_COMPLAINT,
	CONTEST_READY,
	CONTEST_START,
	CONTEST_START_AWARDING,
	CONTEST_END_REQUEST_ACCEPTING,
	CONTEST_START_REQUEST_ACCEPTING,
	CONTEST_END_WORK_ACCEPTING,
	CONTEST_START_WORK_ACCEPTING,
	CONTEST_END_VOTING,
	CONTEST_START_VOTING,
	CONTEST_FINISHED,
	CONTEST_FREEZED,
	MEDIAFILE_ADDED,
	TOUR_DATE_STARTED,
	WORK_SUBMITTED,
	WORK_ACCEPTED,
	WORK_VOTED,
	WORK_WON,
	WORK_COMMENTED,
	WORK_COMPLAINT,
	PARTNER_INVITE_ACCEPTED,
	PARTNER_QUIT,
	GUATANTEE_INVITE_ACCEPTED,
	GUATANTEE_QUIT,
	PROPONENT_INVITE_ACCEPTED,
	PROPONENT_QUIT;

}
